version: '3.8'
services:
  web:
    image: janfalih/santapan-payment-service
    container_name: santapan-payment-service-api
    ports:
      - 9092:80
    networks:
      - santapan-network

networks:
  santapan-network:
    driver: bridge
